### ISSUE TITLE
Beta release of IFACER

### ISSUE THREAD

**Issue by jaromil** [interfacerproject/interfacer-docs#7]
Stage a beta instance online that includes everything we deem as beta.

Release date: **Wed. 12 April**

Includes the promise of not deleting the DB for development reasons -> force use of migrations after a last final reset.

Done: tag software release versions (done) and instructions.

Todo: ChangeLog.

Code of Conduct:
- https://dev1galaxy.org/viewtopic.php?id=17 (nocodeofconduct)
- https://github.com/dyne/.github/blob/main/.github/CODE_OF_CONDUCT.md

DevOps: involve alv and setto

Communication: decide a date miha and andrea coordinating

**Comment by tm-miha** [comment]
+ cancel invitation key at sign up

**Comment by protodeniz** [comment]
@albertolerda how the situation on this?  Can you close this down if we've done it?

**Comment by protodeniz** [comment]
> @albertolerda how the situation on this? Can you close this down if we've done it?

@albertolerda ping.

```
    _
   | |
  ----- 
  (U_o)\
 \ _|_ /
    |
  _/ \_
```

**Comment by albertolerda** [comment]
Matteo is working on the cron for losh import, as soon as it works we have finished

**Comment by protodeniz** [comment]
> Matteo is working on the cron for losh import, as soon as it works we have finished

(>^.^)> <(^.^<)

**Comment by matteo-cristino** [comment]
Loshifacer cronjob is done 👷 today or tomorrow we can test it, then erase the DB and restart everything 🚀
